### ISSUE TITLE
Maybe some slight errors in code

### ISSUE THREAD

**Issue by cocoshe** [OSVAI/GridConv#4] opened 2023-11-25 13:49 UTC
Thanks for your great work! 
I find some error here when I run the code, and here are the errors and solutions (maybe only for me?)

modify
https://github.com/OSVAI/GridConv/blob/2b74889d379e2c94160a36eb28398a6368afbcc6/src/dataset/human36m.py#L33-L34

to

```python
cur_data_2d = torch.load(os.path.join(data_path, data_2d_file), encoding='Latin1')
cur_data_3d = torch.load(os.path.join(data_path, data_3d_file), encoding='Latin1')
```

and
https://github.com/OSVAI/GridConv/blob/2b74889d379e2c94160a36eb28398a6368afbcc6/src/network/gridconv.py#L89-L93

to
```python
self.donut_conv = nn.Conv2d(in_channels=in_channels, out_channels=out_channels, kernel_size=kernel_size,
                          padding=[kernel_size // 2, kernel_size // 2], padding_mode='circular', bias=bias)
self.tablet_conv = nn.Conv2d(in_channels=in_channels, out_channels=out_channels, kernel_size=kernel_size,
                           padding=[kernel_size // 2, kernel_size // 2], padding_mode='zeros', bias=bias)
```

**Comment by kyang-06** [comment] 2023-12-13 08:54
Yes, it depends on python and pytorch version. The released code is compatible for py27 & pytorch1.4, while your revision works for pytorch > 1.8 (if I remember correctly).
Thanks for the complementation, maybe useful for others :)

**Comment by cocoshe** [comment] 2023-12-13 09:09
> Yes, it depends on python and pytorch version. The released code is compatible for py27 & pytorch1.4, while your revision works for pytorch > 1.8 (if I remember correctly). Thanks for the complementation, maybe useful for others :)

Tks for your reply~, but would the version problem or the `encoding='latin1'` influence the result? I try to reproduce the result with py3 and some latest pytorch but somehow seems failed ([more detail in my another issue here](https://github.com/OSVAI/GridConv/issues/5)). Also I tried the [environment.yml](https://github.com/OSVAI/GridConv/blob/main/environment.yml) to build the whole conda env with py2, but the conda can't index some of the dependencies in yaml(pytorch, torchvision, torchaudio, for example, maybe they are out of date)

So is there any training log left? Or any suggestions on producing the result?
Really appreciate~

**Comment by kyang-06** [comment] 2023-12-14 05:34
`encoding` has no influence on the performance. 
You can find my suggestion in your referred issue.
Here is a training log for hrnet_dgridconv_AutoGrids:

> epoch	lr	loss_train	loss_test	err_test	err_x	err_y	err_z	
1	0.0010	0.0385	0.0488	296.1125	75.8109	199.3963	143.6313	
2	0.0010	0.0439	0.0455	265.8105	72.4859	163.4697	134.2171	
3	0.0010	0.0455	0.0451	262.9287	77.9663	158.7633	129.3240	
4	0.0010	0.0450	0.0446	258.5224	78.8347	155.1028	125.5446	
5	0.0010	0.0444	0.0464	260.4237	76.2741	165.9544	122.6475	
6	0.0010	0.0434	0.0460	256.9943	73.1171	166.4856	120.4759	
7	0.0010	0.0427	0.0450	242.2475	62.9558	159.7364	113.8730	
8	0.0010	0.0421	0.0448	242.2933	60.2010	164.9709	112.0135	
9	0.0010	0.0416	0.0490	261.9519	67.2519	180.8174	116.6908	
10	0.0010	0.0411	0.0442	232.4256	58.0736	155.6501	107.8155	
11	0.0009	0.0407	0.0484	254.3649	64.6168	177.8439	111.1913	
12	0.0009	0.0403	0.0441	231.0975	57.9405	155.2385	106.6227	
13	0.0009	0.0400	0.0398	210.9901	44.8900	148.0531	95.9204	
14	0.0009	0.0398	0.0395	205.5291	43.5988	144.2484	93.1630	
15	0.0009	0.0396	0.0394	203.4009	43.5219	142.4611	91.9637	
16	0.0009	0.0393	0.0395	206.3032	45.2096	144.8397	93.0317	
17	0.0009	0.0383	0.0397	209.1935	47.7696	144.4370	95.3269	
18	0.0009	0.0375	0.0398	211.0529	46.9361	145.3159	97.2030	
19	0.0009	0.0369	0.0404	221.1050	49.7893	155.6050	100.7931	
20	0.0009	0.0344	0.0327	193.0582	54.8386	120.1525	94.1617	
21	0.0009	0.0292	0.0327	193.1149	53.3500	120.7511	94.9096	
22	0.0009	0.0279	0.0312	175.3335	47.9422	106.9134	86.1120	
23	0.0009	0.0230	0.0142	149.7090	48.0322	80.1184	85.5575	
24	0.0009	0.0213	0.0227	160.5323	46.6662	86.3672	88.4285	
25	0.0009	0.0221	0.0143	147.6140	42.9623	82.9987	84.0962	
26	0.0009	0.0227	0.0236	164.3380	39.9997	88.7122	95.9165	
27	0.0009	0.0225	0.0244	172.4369	41.9159	91.8664	103.0370	
28	0.0009	0.0225	0.0310	171.1435	38.9638	107.5898	86.9228	
29	0.0009	0.0224	0.0143	146.6273	43.5635	80.1099	83.7891	
30	0.0009	0.0226	0.0168	148.8766	43.1993	81.0752	86.8134	
31	0.0008	0.0227	0.0170	150.1387	42.7214	79.7891	89.2603	
32	0.0008	0.0218	0.0231	156.8367	29.9924	81.6934	97.3653	
33	0.0008	0.0211	0.0226	151.8681	29.1885	80.8528	92.6760	
34	0.0008	0.0206	0.0219	143.9837	27.4500	82.3356	83.5701	
35	0.0008	0.0203	0.0216	140.2606	28.1733	81.1518	79.9869	
36	0.0008	0.0201	0.0301	158.9964	30.5110	109.1320	76.8475	
37	0.0008	0.0199	0.0139	138.8802	29.8528	71.7832	89.2766	
38	0.0008	0.0197	0.0221	148.8764	27.8246	80.2098	90.3598	
39	0.0008	0.0196	0.0309	170.6370	32.5793	114.6069	85.4801	
40	0.0008	0.0196	0.0296	150.3904	28.5499	103.9346	71.4003	
41	0.0008	0.0196	0.0219	144.8593	25.9714	78.9707	86.9441	
42	0.0008	0.0194	0.0308	180.4644	31.0993	112.8474	94.4349	
43	0.0008	0.0193	0.0217	142.0589	26.0486	84.0369	80.9228	
44	0.0008	0.0195	0.0300	156.7642	30.2370	108.3944	75.1436	
45	0.0008	0.0194	0.0206	127.6690	24.5958	76.4555	70.1406	
46	0.0008	0.0193	0.0217	142.2271	25.5931	79.7171	84.0380	
47	0.0008	0.0194	0.0257	158.3893	28.2093	105.9763	77.8680	
48	0.0008	0.0194	0.0217	140.8707	25.8976	81.2526	81.5904	
49	0.0008	0.0193	0.0209	131.0522	24.9918	79.2263	72.1493	
50	0.0008	0.0183	0.0127	125.4807	27.4693	61.8725	82.0131	
51	0.0008	0.0177	0.0218	142.1969	28.1916	79.0689	83.3884	
52	0.0008	0.0174	0.0207	130.5126	27.1028	78.6379	71.4917	
53	0.0008	0.0171	0.0253	156.0843	29.9857	105.7877	75.4285	
54	0.0008	0.0165	0.0210	136.1075	27.8805	83.3995	74.4445	
55	0.0008	0.0167	0.0164	115.4923	29.4462	58.3001	68.8440	
56	0.0008	0.0165	0.0167	119.2759	31.0320	59.4517	71.7606	
57	0.0008	0.0158	0.0170	121.5507	31.3322	59.5971	74.2171	
58	0.0008	0.0155	0.0214	140.6961	29.0039	85.2836	78.5667	
59	0.0008	0.0151	0.0079	101.9661	30.1241	40.0179	70.8736	
60	0.0008	0.0151	0.0081	103.4289	31.4168	42.0932	70.5341	
61	0.0008	0.0153	0.0081	103.1720	31.4207	43.5024	69.3844	
62	0.0008	0.0153	0.0078	100.0911	30.4982	40.9974	67.8399	
63	0.0008	0.0152	0.0073	95.6702	28.7104	39.1084	65.1040	
64	0.0008	0.0146	0.0044	93.5790	37.6982	33.4564	63.7392	
65	0.0008	0.0131	0.0034	79.8929	35.2382	22.0330	56.2041	
66	0.0008	0.0111	0.0031	76.2633	32.6173	19.0152	55.6717	
67	0.0008	0.0090	0.0093	104.6676	35.9006	47.0869	61.3780	
68	0.0008	0.0080	0.0032	77.1620	33.2458	21.2665	54.8034	
69	0.0008	0.0088	0.0033	79.5209	34.4729	23.5216	55.4175	
70	0.0008	0.0101	0.0101	116.7386	38.3904	56.3477	68.4537	
71	0.0007	0.0115	0.0031	78.2559	32.7831	20.6876	56.9449	
72	0.0007	0.0125	0.0046	95.2108	37.5515	30.0925	67.8318	
73	0.0007	0.0130	0.0047	94.9346	36.8610	26.2805	70.3543	
74	0.0007	0.0133	0.0041	88.0026	36.0700	23.1403	64.5176	
75	0.0007	0.0134	0.0044	91.5324	35.5612	24.6690	68.1658	
76	0.0007	0.0133	0.0041	88.7736	36.6139	23.6259	64.6716	
77	0.0007	0.0133	0.0044	92.2180	38.0062	23.6622	67.7693	
78	0.0007	0.0131	0.0049	96.8663	39.4191	25.1775	71.2484	
79	0.0007	0.0130	0.0037	84.0867	36.4608	23.0168	59.8105	
80	0.0007	0.0072	0.0060	72.9188	26.8589	25.3076	51.9114	
81	0.0007	0.0036	0.0019	58.5538	23.4213	15.9028	43.3407	
82	0.0007	0.0044	0.0022	62.8228	23.6570	19.0906	46.3630	
83	0.0007	0.0019	0.0012	42.5921	11.3873	10.9498	35.8252	
84	0.0007	0.0008	0.0011	41.2149	9.5125	10.0529	35.7393	
85	0.0007	0.0007	0.0011	40.4079	9.0933	10.0935	34.9503	
86	0.0007	0.0007	0.0011	41.2802	8.5381	10.0900	36.2682	
87	0.0007	0.0007	0.0012	42.1489	8.1483	10.0461	37.4371	
88	0.0007	0.0006	0.0010	38.6478	7.9534	9.4427	33.9101	
89	0.0007	0.0006	0.0011	41.2209	8.2422	9.8165	36.4824	
90	0.0007	0.0006	0.0011	41.1873	8.4111	10.0270	36.1804	
91	0.0007	0.0006	0.0010	39.0602	7.8220	9.3079	34.4811	
92	0.0007	0.0006	0.0011	40.5784	7.8068	9.2009	36.2452	
93	0.0007	0.0005	0.0010	38.9321	7.1776	9.2859	34.6574	
94	0.0007	0.0006	0.0010	39.4523	7.7836	9.1239	35.1218	
95	0.0007	0.0006	0.0010	38.7000	7.4251	9.2010	34.3731	
96	0.0007	0.0006	0.0012	42.9929	7.7988	10.6990	38.0390	
97	0.0007	0.0006	0.0011	41.6369	7.6291	9.7266	37.2737	
98	0.0007	0.0005	0.0011	39.8569	7.1305	9.4462	35.6223	
99	0.0007	0.0005	0.0011	40.5055	7.3636	9.5328	36.2498	
100	0.0007	0.0005	0.0010	38.5658	7.1534	8.7827	34.5549	
101	0.0006	0.0005	0.0011	39.5677	7.2415	9.1677	35.4072	
102	0.0006	0.0005	0.0010	38.5633	6.9752	9.2956	34.3792	
103	0.0006	0.0005	0.0010	38.5446	7.0830	9.5657	34.1788	
104	0.0006	0.0005	0.0010	37.2928	6.9657	8.5839	33.3495	
105	0.0006	0.0005	0.0010	38.4879	6.8281	9.3537	34.3484	
106	0.0006	0.0005	0.0010	39.6547	7.0100	8.9043	35.7226	
107	0.0006	0.0005	0.0009	36.7887	6.8230	8.6941	32.8011	
108	0.0006	0.0005	0.0009	37.1044	6.9808	8.4966	33.1855	
109	0.0006	0.0005	0.0010	38.7377	6.7962	9.7909	34.3386	
110	0.0006	0.0005	0.0009	36.9481	6.5004	8.9710	32.9606	
111	0.0006	0.0005	0.0010	39.4202	7.1164	8.9327	35.4611	
112	0.0006	0.0005	0.0010	39.2304	6.9602	8.9966	35.2835	
113	0.0006	0.0005	0.0010	38.6872	6.8947	8.8385	34.7753	
114	0.0006	0.0005	0.0009	36.8878	6.4702	8.4029	33.1693	
115	0.0006	0.0004	0.0010	37.1083	6.5803	8.8476	33.1509	
116	0.0006	0.0005	0.0009	36.9524	6.7076	8.9353	32.8919	
117	0.0006	0.0005	0.0010	38.1768	6.8704	8.5666	34.4101	
118	0.0006	0.0005	0.0011	40.5675	7.1207	9.3654	36.4728	
119	0.0006	0.0004	0.0011	39.5347	6.9575	8.7204	35.7191	
120	0.0006	0.0004	0.0010	39.6086	7.1353	9.0722	35.6381	
121	0.0006	0.0004	0.0011	40.9208	7.2228	9.9164	36.4892	
122	0.0006	0.0004	0.0010	37.9825	6.5831	9.1964	33.9974	
123	0.0006	0.0004	0.0010	37.3988	6.5226	8.6978	33.6241	
124	0.0006	0.0004	0.0010	38.7751	6.7058	9.3017	34.7021	
125	0.0006	0.0004	0.0011	40.5906	6.7928	8.6735	36.9574	
126	0.0006	0.0004	0.0010	38.5451	6.6345	8.4700	34.8802	
127	0.0006	0.0004	0.0011	40.2900	6.8071	8.7100	36.5894	
128	0.0006	0.0004	0.0010	38.0694	6.7358	8.7022	34.2336	
129	0.0006	0.0004	0.0011	39.9285	6.7376	8.8134	36.1903	
130	0.0006	0.0004	0.0011	39.9668	6.8143	8.7342	36.2042	
131	0.0006	0.0004	0.0010	38.1238	6.6234	9.7511	33.7011	
132	0.0006	0.0004	0.0010	38.6865	6.8108	9.7565	34.2221	
133	0.0006	0.0004	0.0010	38.4818	6.4918	9.4102	34.2990	
134	0.0006	0.0005	0.0011	39.9790	7.0938	9.8880	35.4539	
135	0.0006	0.0005	0.0010	38.0519	6.7158	9.9445	33.4711	
136	0.0006	0.0005	0.0010	37.6644	6.6367	9.3893	33.4225	
137	0.0006	0.0006	0.0010	38.0355	6.6477	8.9835	34.0526	
138	0.0006	0.0005	0.0010	39.5439	6.6812	9.2225	35.5593	
139	0.0006	0.0005	0.0010	37.8412	6.2307	9.5664	33.6834	
140	0.0006	0.0005	0.0009	36.3864	6.3857	8.7918	32.4472

**Comment by kyang-06** [comment] 2023-12-15 07:30
This issue is moving in the direction of a duplicate of #5. To avoid confusion and consolidate discussion, I will close this one.

**Closed as completed by kyang-06** 2023-12-15 07:30 UTC
